import csv
from datetime import datetime
import os


def export_to_spice(component_name, v_data, i_data, output_path, temp=None):
	"""
	Generates a SPICE netlist (.lib) containing a subcircuit (.SUBCKT)
	that models the measured V-I characteristics using a Piecewise Linear (PWL) source.

	The model uses a Voltage-Controlled Current Source (G-source) controlled by V(1, 2).

	Args:
		component_name (str): Name of the component.
		v_data (list): List of measured voltage points (V).
		i_data (list): List of measured current points (A).
		output_path (str): Full path to save the .lib file.
		temp (float, optional): Temperature data (unused in this model).

	Returns:
		str: The path to the saved .lib file.
	"""

	# Use the provided output_path to get the filename for the .lib directive
	filename = os.path.basename(output_path)

	# Explicitly open the file with UTF-8 encoding
	with open(output_path, 'w', encoding='utf-8') as f:
		f.write(
			f"* SPICE Library Model for {component_name} – Measured {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
		f.write("* Model generated by PPK2 SMU Export Tool\n\n")

		# Define the subcircuit name (ensure SPICE compatibility)
		subckt_name = component_name.replace(' ', '_').replace('-', '_').replace('(', '').replace(')', '')

		# .SUBCKT Directive (2 terminals: 1 and 2)
		f.write(f".SUBCKT {subckt_name} 1 2\n")
		f.write("* G_MEAS implements the measured I(V) characteristic using a PWL function.\n")
		f.write("* G_MEAS: Node 1 is the positive terminal, Node 2 is the negative terminal.\n")
		f.write("* Control voltage is V(1, 2).\n")

		# PWL G-source implementation: G<name> <+out> <-out> VALUE={... PWL(V_control, V1, I1, V2, I2, ...)}
		f.write("G_MEAS 1 2 VALUE={\n")
		f.write("    + PWL(V(1, 2),\n")

		# Write the V-I pairs (V(control), I(output))
		for i, (v, current) in enumerate(zip(v_data, i_data)):
			# Use '+' for continuation lines in SPICE
			line_end = ',' if i < len(v_data) - 1 else ''
			# SPICE PWL values must be formatted precisely (using E notation for robustness)
			f.write(f"    + {v:.6E}, {current:.9E}{line_end}\n")

		f.write("    + )\n")  # Closing parenthesis for PWL
		f.write("    }\n")  # Closing brace for VALUE

		# .ENDS Directive
		f.write(f".ENDS {subckt_name}\n\n")

		# Library definition for easy inclusion in SPICE simulators
		f.write(f".lib {filename} {subckt_name}\n")

	return output_path